### ISSUE TITLE
ansible failing to create temporary directory with ubuntu VM

### ISSUE THREAD

**Issue by pmores** [alicefr/kata-local-ci-setup#12]
I'm running into a problem. The VM creation

`virt-build-kata -d ubuntu -k <...> -o kata-ci-ubuntu.qcow2`

goes well but then ansible fails pretty much immediately with

`fatal: [192.168.122.249]: UNREACHABLE! => {"changed": false, "msg": "Failed to create temporary directory.In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo /home/kata/.ansible/tmp `\"&& mkdir \"` echo /home/kata/.ansible/tmp/ansible-tmp-1621497642.2791765-263890-25594791683090 `\" && echo ansible-tmp-1621497642.2791765-263890-25594791683090=\"` echo /home/kata/.ansible/tmp/ansible-tmp-1621497642.2791765-263890-25594791683090 `\" ), exited with result 1", "unreachable": true}`

Creating the VM, I requested Ubuntu and ended up with 18.04.5. I have changed the VM IP addresss in hosts.yaml to match my actual VM but otherwise I believe I'm following the instructions. @alicefr Any ideas what I'm doing wrong? (Sorry if it's something obvious - this is my first time with ansible...)

**Comment by alicefr** [comment]
@pmores that's weird. It seems the permissions on the directory ` /home/kata/.ansible/tmp` are not correct. Could you please ssh in the VM and check the directory permissions:
```bash
$ ssh kata@kata-ubuntu
kata@kata-ubuntu-18:~$ ls -lsh .ansible
total 4.0K
4.0K drwx------ 3 kata kata 4.0K May 25 06:42 tmp
```

**Comment by alicefr** [comment]
Otherwise, you need to change the remote_tmp variable in your `ansible.cfg`. See: https://stackoverflow.com/questions/35176548/authentication-or-permission-failure-did-not-have-permissions-on-the-remote-dir

**Comment by pmores** [comment]
@alicefr There was actually no `.ansible` directory there.  Upon closer examination I noticed that `/home/kata` was owned by `root:root`.  Is that something I could have caused somehow?

Also, after `sudo chown kata:kata /home/kata` I re-run ansible.  Now it got past the Gathering Facts task but failed subsequently with

`TASK [Synchronize kata-containers repo] ********************************************************************
fatal: [192.168.122.249]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --out-format=<<CHANGED>>%i %n%L /root/go/src/github.com/kata-containers/kata-containers rsync://kata@192.168.122.249/kata", "msg": "rsync: [sender] change_dir \"/root/go/src/github.com/kata-containers\" failed: No such file or directory (2)\nrsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1330) [sender=3.2.3]\n", "rc": 23}`

There really isn't a `/root/go` directory there.  Could this also be an ownership/permissions issue?

**Comment by alicefr** [comment]
@pmores the permission should be set by https://github.com/alicefr/kata-local-ci-setup/blob/master/virt-build-kata#L108, so probably something went wrong there

**Comment by alicefr** [comment]
There is also something weird with the user as everything should be run under kata user and not root

**Comment by alicefr** [comment]
@pmores do you mind to re-run the `virt-build-kata` script and copy the output? Thanks

**Comment by pmores** [comment]
@alicefr Will do but just to make sure:
- is the `virt-build-kata` command line OK, can I use that again?
- which (host) user should the `virt-build-kata` run under?

Thanks!

**Comment by alicefr** [comment]
yes, you can reuse it. Just remove the VM in use by libvirt otherwise the image is locked. I run the script with sudo because of virt-install and I want to reuse the default network. But you can also use it as standard user and configure the network

**Comment by pmores** [comment]
@alicefr Here's the output of the `virt-build-kata` command:

```
[root@localhost kata-local-ci-setup]# ./virt-build-kata -d ubuntu -k /home/pvl/.ssh/id_rsa.pub -o kata-ci-ubuntu.qcow2
+ virt-builder ubuntu-18.04 -o kata-ci-ubuntu.qcow2 --format qcow2 --size=50G --root-password password:kata --firstboot-command 'usermod -a -G sudo kata' --update --firstboot-command dhclient --firstboot-command 'systemctl enable serial-getty@ttyS0' --firstboot-command 'systemctl start serial-getty@ttyS0' --mkdir /home/kata --delete /.autorelabel --ssh-inject root:file:/home/pvl/.ssh/id_rsa.pub --install git,rsync,curl,make,tar --firstboot-command 'useradd -m  kata -s /bin/bash' --firstboot-command 'echo "kata ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/kata' --firstboot-command 'echo '\''export PATH=$PATH:/usr/local/go/bin'\'' >> /home/kata/.bashrc' --firstboot-command 'mkdir -p /home/kata/.ssh' --firstboot-command 'echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKBW8LcDfsEVeRIm9zkNRuWsaxSXssIejOU29PldxPCOz4mGKC6MTCfARbYgW0jFtHh/m3mwZxKUvhrA9kzkC+GlRIUiQg7wgiaWQlnRBrSD1+pgRCsc157DM92vXi+rY3l8JW+BO/T0AyygZsVyPT/wEceJYW0p/XLvmgDHAw6iqmkr8htztp85xdBcCBlEqov049IoHHKW9tE46t41t+KgT5hoKY2poEZnc8gqFgOJHvLU/cdus9wuufxDS/clHVRUzUMGh5zy6BQIZyX4WhPYnuSwn+yU5HGcAv9TcsuO7yDujZmQHvlOkMllkubPxVZLpCc5zzPUuf7TwwgVVrDxv0eNhywDsVALfz+VF0Rz7MXAIXuoTCqLgISJzl5KD5kw7XlKdVHt94WNvmQDcvkE2wvBOFGrAYqN5QIFDPznDgtcxcF77E39vNYf8HRAGxTm8LZRQ3WYXtIExyZ4q0jDLCZzWuEegtX9I6CPBNmw/L7urFtfS32scKNIFVO/U= pvl@localhost.localdomain > /home/kata/.ssh/authorized_keys' --firstboot-command 'chown kata:kata -R /home/kata "${final_firstboot_cmd[@]}"' --password kata:password:kata --hostname kata-ubuntu-18.04
[   1.8] Downloading: http://builder.libguestfs.org/ubuntu-18.04.xz
[   2.3] Planning how to build this image
[   2.3] Uncompressing
[   8.7] Resizing (using virt-resize) to expand the disk to 50.0G
[  31.6] Opening the new disk
[  35.7] Setting a random seed
virt-builder: warning: random seed could not be set for this type of guest
[  35.7] Installing firstboot command: usermod -a -G sudo kata
[  35.8] Updating packages
[ 225.4] Installing firstboot command: dhclient
[ 225.5] Installing firstboot command: systemctl enable serial-getty@ttyS0
[ 225.5] Installing firstboot command: systemctl start serial-getty@ttyS0
[ 225.6] Making directory: /home/kata
[ 225.6] Deleting: /.autorelabel
[ 225.6] SSH key inject: root
[ 226.3] Installing packages: git rsync curl make tar
[ 241.4] Installing firstboot command: useradd -m  kata -s /bin/bash
[ 241.4] Installing firstboot command: echo "kata ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/kata
[ 241.4] Installing firstboot command: echo 'export PATH=$PATH:/usr/local/go/bin' >> /home/kata/.bashrc
[ 241.5] Installing firstboot command: mkdir -p /home/kata/.ssh
[ 241.5] Installing firstboot command: echo ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDKBW8LcDfsEVeRIm9zkNRuWsaxSXssIejOU29PldxPCOz4mGKC6MTCfARbYgW0jFtHh/m3mwZxKUvhrA9kzkC+GlRIUiQg7wgiaWQlnRBrSD1+pgRCsc157DM92vXi+rY3l8JW+BO/T0AyygZsVyPT/wEceJYW0p/XLvmgDHAw6iqmkr8htztp85xdBcCBlEqov049IoHHKW9tE46t41t+KgT5hoKY2poEZnc8gqFgOJHvLU/cdus9wuufxDS/clHVRUzUMGh5zy6BQIZyX4WhPYnuSwn+yU5HGcAv9TcsuO7yDujZmQHvlOkMllkubPxVZLpCc5zzPUuf7TwwgVVrDxv0eNhywDsVALfz+VF0Rz7MXAIXuoTCqLgISJzl5KD5kw7XlKdVHt94WNvmQDcvkE2wvBOFGrAYqN5QIFDPznDgtcxcF77E39vNYf8HRAGxTm8LZRQ3WYXtIExyZ4q0jDLCZzWuEegtX9I6CPBNmw/L7urFtfS32scKNIFVO/U= pvl@localhost.localdomain > /home/kata/.ssh/authorized_keys
[ 241.5] Installing firstboot command: chown kata:kata -R /home/kata "${final_firstboot_cmd[@]}"
[ 241.6] Setting the hostname: kata-ubuntu-18.04
[ 242.4] Setting passwords
[ 243.2] Finishing off
                   Output file: kata-ci-ubuntu.qcow2
                   Output size: 50.0G
                 Output format: qcow2
            Total usable space: 49.2G
                    Free space: 47.1G (95%)
+ opts=
+ '[' '!' -z '' ']'
+ virt-install --import --name kata-ubuntu --memory 8192 --vcpus 4 --disk path=kata-ci-ubuntu.qcow2,format=qcow2 --os-variant=ubuntu18.04 --noautoconsole

Starting install...
Domain creation completed.
```

**Comment by alicefr** [comment]
@pmores aah I see, I guess you are missing a fix from @c3d's https://github.com/alicefr/kata-local-ci-setup/pull/11. Could you please try to pull the latest version of the repo.

**Comment by alicefr** [comment]
The problem is:
```
[ 241.5] Installing firstboot command: chown kata:kata -R /home/kata "${final_firstboot_cmd[@]}"
```

**Comment by pmores** [comment]
@alicefr Thanks, it worked! :-)  Sorry about my failure to get the very latest before complaining. :-(

**Comment by alicefr** [comment]
@pmores no worries :) happy that it worked
