### ISSUE TITLE
virt-build-kata: don't hardcode the VM name

### ISSUE THREAD

**Issue by fidencio** [alicefr/kata-local-ci-setup#2]
Quite similar to https://github.com/alicefr/kata-local-ci-setup/issues/1, I'd suggest using `kata-$d` as the VM name. Here we don't have to explicitly check for the name as virt-install would just stop in case there's already a VM with such name.

**Comment by alicefr** [comment]
Yes, I modified the behavior and the VM name now is kata-<distro>
